name: integration-tests

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: "1.11.1.1139"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq lsof coreutils

      - name: Install Rust and websocat for WebSocket tests
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo install websocat

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            .cpcache
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Run integration tests
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          echo "Current directory: $(pwd)"
          echo "Script path: ./test/scripts/integration-tests.sh"
          chmod +x ./test/scripts/integration-tests.sh
          ./test/scripts/integration-tests.sh
        shell: /usr/bin/bash -e {0}
