name: integration-tests

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: "1.11.1.1139"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            .cpcache
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-

      - name: Run integration tests
        run: |
          echo "Current directory: $(pwd)"
          echo "Script path: ./test/scripts/integration-tests.sh"
          ls -la ./test/scripts/
          chmod +x ./test/scripts/integration-tests.sh
          ./test/scripts/integration-tests.sh
        shell: /usr/bin/bash -e {0}